### ISSUE TITLE
Add contribution guideline and issue templating to the repository

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#1107]
We still have no issue templating and contribution guidelines. It would be good to move forward here. 
I would propose the following:

- Issue template bug
- Issue template new feature idea
- Issue template concrete task
- Blank or generic template for other issues.

This list might not be complete and deserves discussion. In the next step I believe we can discuss the contribution guideline.

**Comment by metemaddar** [comment]
Thanks for assign this valuable and attractive task also to me while it gives me great sight over the issues/PR process.
I've created a PR to add issue templates. So we can check it and also edit the templates there. The templates are created from the default examples and the following references.

## Add templates for PRs also
We can also have issue templates for PRs which also have guidelines to auto-close related issues, summaries, and more.

## For blank template
As I found in the tutorials, We will always have a button under the whole templates to create a blank issue. However maybe it is good to create a blank template in order to have big button for it. Although not creating a blank template may lead the creator to first focus on specific templates first.

## Example issue template repository
Found this great repository which has examples for technical aspects to create issue/PR templates: https://github.com/stevemao/github-issue-templates
Used for Bug report template

## More links
I found some great videos about issue templates:
1. [GitHub Issue Templates - GitHub Project Management Tutorial](https://www.youtube.com/watch?v=UPsCXqxxJUA)
2. [Get started with GitHub issue forms - GitHub Checkout](https://www.youtube.com/watch?v=qQE1BUkf2-s)

Also there is a good [guideline to create tasks](https://tilburgsciencehub.com/building-blocks/collaborate-and-share-your-work/project_management/write-good-issues/). However I think we have most of them, but I was thinking that if we could have external guideline links at template, it would be a good help in some situations.
A very simple yet useful template from the above link is used to create new tasks.

**Comment by EPajares** [comment]
Thanks a lot, @metemaddar for this great research! All of it is interesting. I would propose that you could maybe check what would be needed from your opinion. I mean we can start small with some templates for the most common issues and then expand it in the future. Also concerning PRs, it would be good to have a template. Some automation like autoclosing issue would also be interesting so maybe we could check which workflows would be suitable for this.

**Comment by metemaddar** [comment]
I'm very agree about starting with simple templates as they can better fit to our needs in the future.
Now we have:

- [Pull Request template](https://github.com/goat-community/goat/blob/main/.github/PULL_REQUEST_TEMPLATE.md)
    - It works also on a forked repository PR to GOAT.
- Concrete task template
- Feature request template
- Bug report template
- Bug report form

I think it's not bad to have both forms and templates for a topic category. But however it can make issue creation crowded.

## And about screenshots
It could be added inside any parts of the form as all parts are markup editable. For example it can be part of the (Current behavior). But I could not find the screenshot (attachment) button at first (Maybe it's a policy of git communities to get less files maybe). I think we would discuss about how to encourage or remind the reporter to put screenshots. Maybe inside comments.

**Comment by EPajares** [comment]
Thanks a lot for adding the templates to this and the other repos. I believe they are very good. So I will close this issue now.
