### ISSUE TITLE
Write endpoints for managing layers

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#1325]
The layers including styles, translations, etc. are currently managed via several tables: customer.layer_library, customer.layer_source, customer.style_library, basic.study_area. There should be created several endpoints to read, add and modify layers. Separate issues will be opened for each of them. 

The endpoint should be added under the Layer Group like the following:

`layers/config`

**Comment by metemaddar** [comment]
I suggest to not using config in the URI. Because the endpoints which are specified are explicitly CRUD. Also at the other hand, we need to specify type of config while using 'config' keyword which can make it a bit complex.

However as we want to specify these endpoints are for configurations, I suggest to use config either before layer. I mean `config/layers/library` or simply add the specified endpoints to the Config category.

What is your opinion @EPajares?

**Comment by EPajares** [comment]
Generally, this could make sense. Though we have to consider that we are having more endpoints that are manipulating somehow the configuration. They are currently under customization though these customizations are currently on the user level and not the global level as the layers. So I would agree to do it as you proposed.
