### ISSUE TITLE
Write endpoint to add layer to study area

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#1331]
Linking to issue #1325. After layers are created they have to be added to one or more study areas. Each study area has one setting object. Here we are adding the layers as JSON. Meanwhile, the layers groups are fixed: 

  buildings_landuse
  street_level_quality
  environmental_quality
  additional_data
  basemap
  heatmap

**Comment by metemaddar** [comment]
To add a `layer` to a `study_area` I think it would be good to create an endpoint in category of study_area. Because we are manipulating a study_area. And as a response it will return a study_area object. If we find this way correct, I think it would be better to do it while creating other endpoints of study_area. @EPajares

**Comment by EPajares** [comment]
As discussed we believe it could be better to add it to the layer group: 
![image](https://user-images.githubusercontent.com/42171996/171805899-db2f5876-31e5-41ea-9969-9b2adbf60d48.png)

For now we would only need a PUT that updates the setting field. Actually the other fields we should not be able to update. We could add it under following URL: `api/v1/layers/study_area/config `
