### ISSUE TITLE
[GITHUB FLOW] red checks while PR

### ISSUE THREAD

**Issue by metemaddar** [goat-community/goat#1486]
### Problem
I was curious about the red tests of GitHub flows while checking the PR.
I found the following output error of the GitHub:
```
Run make build-docker-image -e COMPONENT=api
  make build-docker-image -e COMPONENT=api
  shell: /usr/bin/bash -e {0}
  env:
    DOCKER_USERNAME: 
    DOCKER_PASSWORD: 
    FONTAWESOME_NPM_AUTH_TOKEN: 
/usr/bin/docker  build -f app/api/Dockerfile --pull -t docker.io/goatcommunity/api-HEAD:ef6cdb6 app/api
invalid argument "docker.io/goatcommunity/api-HEAD:ef6cdb6" for "-t, --tag" flag: invalid reference format: repository name must be lowercase
See 'docker build --help'.
make: *** [Makefile:80: build-docker-image] Error 125
Error: Process completed with exit code 2.
```

As error says the problem was happened by the keyword: HEAD
And this error occurred in makefile line 80
https://github.com/goat-community/goat/blob/e00de0ddd444bc11050cc8cbc953459f57043c21/Makefile#L80

As the DOCKER_IMAGE is created by:
https://github.com/goat-community/goat/blob/e00de0ddd444bc11050cc8cbc953459f57043c21/Makefile#L30

And the HEAD as came from NAMESPACE created by:
https://github.com/goat-community/goat/blob/e00de0ddd444bc11050cc8cbc953459f57043c21/Makefile#L13

####  Proposed Solution
As the last line should return the source branch of PR, but it returns HEAD instead. I don't know why this happens.
But as I was thinking the NAMESPACE should be one of `dev`, `staging` and `prod` as mentioned in the MakeFile. So I think in the PR, maybe we should pull form the target branch instead of source.

To achieve this I think we can pass the NAMESPACE to the MakeFile in the PR.yaml to override the NAMESPACE while building the image, using the GitHub variable:
`${{ github.event.pull_request.base.ref }}` or `${{ github.base_ref }}` ([ref](https://stackoverflow.com/a/62332270/1951027))

**Comment by majkshkurti** [comment]
@metemaddar Thank you for bringing this up. The error coming from the Makefile is related to the HEAD being in a detached state. It has a different _**`sha`**_ from the branch's latest commit, and the  `git rev-parse --abbrev-ref HEAD` in this case will just return HEAD, which causes an error in the --tag flag since docker doesn't support capital letters in the repository name. 
However, this is a legacy as we don't need a --tag (-t) flag on the PR workflow when we are not pushing the image in Dockerhub. I can create a new Makefile command without the -t flag. (e.g *build-pr-docker-image*) and it should fix this.

**Comment by metemaddar** [comment]
Thank you very much Majk. It's great.
