### ISSUE TITLE
Endpoints sorting by column and search for each column

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#1597]
# Goal of this issue
Currently, the search function only works for one column. As I have seen for users, it is the e-mail address, this sometimes makes it a bit unflexible. It would be great to have a search field for each column. This could eventually open when the user clicks on the column.

Furthermore, it would be good to sort alphabetically the table based on the values in a column.  

# Resources

# Deliverables
New functionality sorting by column and search bar for each column. 

# Branch to derive
Dev

**Comment by cinaaaa** [comment]
@EPajares I'm a bit confused that where exactly you need the search bar, may we have a scheduled meeting for it?

**Comment by EPajares** [comment]
I think we have to do the enpoints first. They should do the following:

- Search that works only on one column (e.g. search all with Name "Majk")
- Sort data alphabetically by column content so we could add a button to sort the data ascending and descending

**Comment by EPajares** [comment]
@metemaddar we can discuss how we should change the endpoints

**Comment by cinaaaa** [comment]
@EPajares Yes, exactly

**Comment by metemaddar** [comment]
Just thinking loud.
I think it's better to add the `ordering` and `like` options to the CRUD base, so that it will apply to all endpoints. I'm also thinking about adding a new class to accept `q` and `ordering` so that we can add it to all endpoints to accept query filters.

But I should be aware of queries to not conflict. Of course when we create an abstract class for them, we can change the name anytime. Also it would be good to take a look at some best practices. One is [here](https://stackoverflow.blog/2020/03/02/best-practices-for-rest-api-design/#h-allow-filtering-sorting-and-pagination) and is like this:

```
/employees?lastName=Smith&age=30

We get:

[
    {
        "firstName": "John",
        "lastName": "Smith",
        "age": 30
    }
]
```

Also it suggests to use page as one of standard parameters. And also need limit parameter. In CRUD Base we have the skip and limit for get_multi and I think it's enough for endpoints. Because we mostly should use get multi for listing items:
https://github.com/goat-community/goat/blob/1fc0bdd8ce4c34412305ab8b0de94a770312f150/app/api/src/crud/base.py#L68-L70

For sorting:
`http://example.com/articles?sort=+author,-datepublished`


### Summary

- [ ] We have implementation for pagination at CRUD and Endpoints, but just need to check.
- [ ] We need query parameters dynamically, but needs to be `like` parameter to get searched.
- [ ] We need sort implementation so that:

   1. Convert `-` sign to order desc
   2. Separate orderings by comma
   3. Add the ordering function to the `get_multi` CRUD method.

**Comment by EPajares** [comment]
Hi Mohammad thanks for summing up the thoughts. All makes sense from my point of view. I believe we should add this additional parameters to be passed to the endpoints as optional parameters. So we could still use the endpoint without them.

**Comment by EPajares** [comment]
One thing that we might have to discuss if we still want to have a search by all columns. Currently, this is implemented in the client.

**Comment by metemaddar** [comment]
> One thing that we might have to discuss if we still want to have a search by all columns. Currently, this is implemented in the client.

There are two scenarios to implement sort/search. Implement at front or back. If we decide to implement search at frontend, then sorting can get implemented at front using the searchable/sort-able tables.
Because to implement search, we need to fetch all rows at front first.

**Comment by metemaddar** [comment]
@EPajares

In Django we have an option to provide search_fields. So whenever you apply a search it will search through the provided fields.

This has some **advantages** like:
- When we are searching for something, but we don't exactly know in which field was happened. For example in name or email.
- The implementation is more straight forward and has less bugs.
- Has simpler user interface at UX. Because we have only one search field.

It has some **cons** like:
- It can be a bit slower. But I‌ think not much slower as we provide the search_fields.

**Comment by metemaddar** [comment]
Now implemented search by `q=search_query` and sort by `sorting=-desc_field,field`

**Comment by metemaddar** [comment]
@cinaaaa 
Search and Sorting is available for users endpoint.

**Comment by metemaddar** [comment]
Search and sort can be easily applied to other list endpoints as well.

**Comment by metemaddar** [comment]
@cinaaaa 
The ordering/search is now available for the following endpoints at branch: [goat-community:feat/endpoints-search-ordering](https://github.com/goat-community/goat/tree/feat/endpoints-search-ordering)

- /config/layers/vector/static
- /config/layers/library/styles
- /config/layers/library
- /config/geostores
- /config/opportunities
- /config/opportunity-study-area
- /ursers
