### ISSUE TITLE
Double check tooltip drawing new feature

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#167]

**Comment by EPajares** [comment]
Drawing new ways is still a bit to complicated for many people. I see following main issues:

- Users don't know that they have to click upload. 
- loading bar is not visible enough
- maybe users should get a message like "network change completed"
- in principle users are used to click ESC to leave e.g. editing mode
- some users expect that the isochrones will be automatically updated after the scenario was updated, we could think about a refresh button for each calculation? This would recompute the isochrone then.
- The type should be road or bridge/underpass for now

- next level would be having a step by step guide to do the scenario.

**Comment by EPajares** [comment]
@EmnaBH @UJehle @majkshkurti  please if you have something to add, don't hesitate,

**Comment by EPajares** [comment]
If you want to see the most recent editing capabilities, here is online-demo for FFB: https://development.open-accessibility.org/

**Comment by UJehle** [comment]
Awesome, looks nice!

I really like the full screen option. And the colour picker for the isochrones. And the routing profiles ;)

I am just wondering, there is no boundary around the study area shown - is that intentional?

[cid:79dac407-84dd-4762-b857-90ffc0d0220f]

And I tried the new scenario for POIs. I changed the position of an amenity and uploaded it, but the heatmap is currently not reacting on it. Or maybe I misunderstood how this works.

The feature for placing new POIs is also nice! Maybe we should therefore provide a short guideline about how to write the opening hours.

And maybe adding a hint about how the editing mode (e.g. drawing new features) can be exited would be useful. I accidentially builded 3 new kindergardens bevore I found which button I have to press haha.


The labeling of the isochrones in the result section (with the adress of the starting point) is also really helpful. Maybe we just have to reduce the font size? On my screen, only half of the adress is displayed. Or we show the whole adress in a infobox that appears when the user hovers the mouse pointer over it.

________________________________
Von: Elias Pajares <notifications@github.com>
Gesendet: Dienstag, 28. Januar 2020 14:09:19
An: goat-community/goat
Cc: Jehle, Ulrike; Mention
Betreff: Re: [goat-community/goat] Double check tooltip drawing new feature (#167)


@EmnaBH<https://github.com/EmnaBH> @UJehle<https://github.com/UJehle> @majkshkurti<https://github.com/majkshkurti> please if you have something to add, don't hesitate,

**Comment by EPajares** [comment]
Thanks. The boundary was a temporary issue with the app-config. It should look good now. 
The POI interaction is not finished yet. Especially the part with the heatmap as this is very resource intensive. 

The other things I think we should try to address. Concerning improvements @majkshkurti  and me we had a skype, we were discussing about different improvements for the scenario building. They will be documented here.

**Comment by EPajares** [comment]
I will close this issue as most the things are already finished. We will open new issues for further improvements.
