### ISSUE TITLE
Fix .gitignore for cache folder containing heatmap matrices

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#1843]
# Goal of this issue
Currently the .gitignore does not work like it should. 
The folder structure should be like:

cache/opportunity_matrices/cycling/standard
cache/opportunity_matrices/walking/standard

We want to ignore the content of the folders:

cache/opportunity_matrices/cycling/standard
cache/opportunity_matrices/walking/standard

But it does not ignore files that are inside the mentioned folders. 

# Resources

# Deliverables

# Branch to derive

**Comment by metemaddar** [comment]
If I get it well, it works for feature/walking-matrix but doesn't work for other branches. It's because the gitignore is different in other branches.
If it's the case other than dev, which the PR will fix, we can fix others by the cherry-pick:
`git cherry-pick ad536a10be673dff7e634441c14b80349eaad86a`

Link to commit: ad536a10be673dff7e634441c14b80349eaad86a

**Comment by EPajares** [comment]
Thanks. I actually had the problem in the feature/walking-matrix branch. Actually, the problem is also that the folder for walking is not even included here: https://github.com/goat-community/goat/tree/feature/walking-matrix/app/api/src/cache/opportunity_matrices

**Comment by metemaddar** [comment]
@EPajares So we need the walking directory there?

**Comment by metemaddar** [comment]
Added all directories that was mentioned in gitignore.
Reference for doing this is [here](https://stackoverflow.com/a/932982/1951027).
