### ISSUE TITLE
Titel Karte Güteklasse

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#2026]
Cannot change the title of a map containing Güteklasse. This seems to be a bug

**Comment by Ebubeker** [comment]
This bug is very difficult to find, since there are almost no signs, and it is very weird. I guess all the heatmaps have the same settings and properties in most of the cases. And it is hard to find something that links it with the v-autocomplete (the one we use to change study areas).

**Comment by Ebubeker** [comment]
@EPajares I dug a little deeper about the problem. I know the issue, but it is very complex to fix and it will acquire major changes into the code.

It is an expected behavior when the v-autocomplete input cannot be changed while a popup with inputs is open, because the v-autocomplete component is designed to lock the input while the popup is open to prevent users from accidentally changing the value.

I can unlock it but still it doesn't work.

**I asked chatgpt and this is what he/she/it suggested**:
Here are some potential solutions you can try:

- Check that the popup component is not blocking the v-autocomplete input. In some cases, the popup component might have a higher z-index than the v-autocomplete component, which can cause it to block user input. You can try increasing the z-index of the v-autocomplete component to ensure that it appears above the popup.
- Ensure that there are no conflicting event handlers or listeners on the v-autocomplete component or its parent components that might be preventing the input from being changed. You can try temporarily removing any event handlers or listeners and see if the input can be changed while the popup is open. Ensure that there are no conflicting event handlers or listeners on the v-autocomplete component or its parent components that might be preventing the input from being changed. You can try temporarily removing any event handlers or listeners and see if the input can be changed while the popup is open.
- Consider redesigning the user interface to avoid having multiple popups open at the same time. In some cases, having multiple popups open simultaneously can be confusing for users and lead to unexpected behavior.

**Update**

I already tried the first point but it doesn't work.

**Comment by EPajares** [comment]
Thanks @Ebubeker for investigating it. I understand. Well then let's leave this as we will focus on the client rewrite in the upcoming sprints
