### ISSUE TITLE
[BUG] Icon selection for POIs not working (Amsterdam)

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#2058]
### Summary 📃

Changing the POI icon & color does not save (Amsterdam version). 

### Expected Behaviour ✔

The selected icon & color is reflected on the map & in the menu. 

### Current Behaviour 🔦

The selected icon & color is not reflected on the map & in the menu. 

### Steps to reproduce 👣

1. Open GOAT Amsterdam (production)
2. Activate some POIs
3. Change icon & color of POI symbol. 
4. See no change ;)

**Comment by metemaddar** [comment]
It seems to be a client error. The API seems to work fine for branch main on local repository.
When I change with the following payload, it returns the changed settings. 

`{"subway_entrance":{"icon":"fas fa-baby","color":["#82E1BE"]}}`

But I couldn't check it correctly at online app. As I have problems due to my local network.

**Comment by metemaddar** [comment]
@majkshkurti 
I mentioned to ask for manage the task to find it's flow.
Thanks

**Comment by EPajares** [comment]
I think this is not a client issue. As from what I see, the payload is correctly sent but the response it not correct as it does not contain the changed icon. In dev it works but yeah we need to check this further in prod.

**Comment by metemaddar** [comment]
Exactly. I think the difference should be the production configurations as the endpoint checks the configurations:
https://github.com/goat-community/goat/blob/05b423e0c46e6568974505de126feef91594d67e/app/api/src/crud/crud_customization.py#L291-L317

**Comment by metemaddar** [comment]
Waiting for sample data.
