### ISSUE TITLE
Revise heatmap examples

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#2086]

**Comment by metemaddar** [comment]
I think it's better to remove the request examples for resolutions higher than 6. The API docs will freeze due to code highlight for huge response. [GitHub issue](https://github.com/swagger-api/swagger-ui/issues/3832)
There are also solutions to remove highlighting for (some 🤔)  endpoints. But it should take some time. [StackOverflow](https://stackoverflow.com/a/75218362/1951027)
✅  Also the higher resolutions are available by modifying the payload.

**Comment by metemaddar** [comment]
Other than this the heatmap examples are working. I think we don't need PR for this.

**Comment by metemaddar** [comment]
Summary of discussion about examples
1. We can add the examples with resolution 6 to the beginning and add a warning to higher resolutions.
2. We still need to test high resolutions to see if there is any bug on them or not.
3. We can test against time of execution to check passing the performance. We need to see if the higher resolutions finish or not ([We can set timeout on unit tests](https://stackoverflow.com/a/34743601/1951027))

Majk also introduced [Smoke testing](https://www.techtarget.com/searchsoftwarequality/definition/smoke-testing)
