### ISSUE TITLE
Implement buffer logic in client

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#2142]

**Comment by AnaSasso** [comment]
Here are the screens for the buffer flow on the live version:
Changes:

- **GEOZONES** instead of **ISOCHRONES**, as we added buffer
-  **Isochrone calculation** to just **calculation**

 <img src="https://user-images.githubusercontent.com/116002158/232074730-333b6be2-11b5-44db-b3db-ba5f1bdddaee.png" width=30% height=30%><img src="https://user-images.githubusercontent.com/116002158/232074731-d0a53fb9-8333-486c-99e5-a27394fc9216.png" width=30% height=30%><img src="https://user-images.githubusercontent.com/116002158/232074734-22830bb0-44d7-4ef0-b8d0-87c775a6480c.png" width=30% height=30%><img src="https://user-images.githubusercontent.com/116002158/232074733-7a28b4fc-5528-42f9-ab68-1e5bcde63c06.png" width=30% height=30%> <img src="https://user-images.githubusercontent.com/116002158/232074732-1c5193ad-8db8-41db-8aaf-98e5fb1a5f44.png" width=30% height=30%>

**Comment by EPajares** [comment]
Catchments
Einzugsbereiche

**Comment by EPajares** [comment]
We will apply a 50m step size and let the use pick up to 3000m max size.

**Comment by AnaSasso** [comment]
> Catchments
> Einzugsbereiche

instead of "Geozones"?

**Comment by EPajares** [comment]
Yes the term is more frequently used. But we can change it directly in the client.
