### ISSUE TITLE
Add layer preview to content

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#2412]

**Comment by baghdasarovnorayr** [comment]
https://github.com/goat-community/goat/pull/2435

**Comment by baghdasarovnorayr** [comment]
![Image](https://github.com/goat-community/goat/assets/138683176/c36aa39d-0664-4189-aabe-e4591a6567a1)


I encountered an issue in the pr.yaml file regarding echoing the changed files. It seems that the problem is related to filenames that include the scope (dashboard). Currently, I have commented out this specific line in the yaml file. If you have any suggestions or solutions for handling filenames with (dashboard) in the scope, please let me know

```
#      - name: Show changed files
#        run: echo ${{steps.get_file_changes.outputs.files}}
```
