### ISSUE TITLE
Enable scenarios with changed way attributes

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#247]
Make it possible to also change way attributes (e.g. lit=no to lit=yes) in a scenario.

**Comment by EPajares** [comment]
This could be a new epic. As we might have several sub-tasks.

**Comment by EPajares** [comment]
For the next testing cycle in Fürstenfeldbruck it would be important to be able to change especially the wheelchair tag.
I would say per default a new way should be wheelchair = 'yes'

**Comment by UJehle** [comment]
@EPajares @majkshkurti what is the progress of this issue?

**Comment by EPajares** [comment]
No real progress so far. UI logic is easy but I still need to build the backend. More work. What we should have by the end of  the week is that new ways are wheelchair=yes. Rest we can do later.

**Comment by EPajares** [comment]
Thanks @majkshkurti! Client side it works. I realized that it would make sense to label features for which only the attributes were changed. Otherwise it is hard to tell if the feature also face modified geometrically. I would propose a new column in the ways_modified table. I think we might have to add this in the future also to the other modified-tables to keep consistancy. I will call the column `edit_type` and we could pass the values `attributes_only, drawn geometry, modified geometry`.
