### ISSUE TITLE
Add feature for translating website German/English

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#278]

**Comment by EPajares** [comment]
Currently the whole homepage is english only. We will not manage to translate everything (e.g. Docs) but the mainpage should be translated.

**Comment by EPajares** [comment]
@ivanchromjak Could you kindly handle this issue.

**Comment by ivanchromjak** [comment]
@EPajares 

Github pages doesn't support any translation plugins, ref https://pages.github.com/versions/ that leaves two options:

1. continue hosting on GitHub pages and put the translated page/pages into a subdirectory eg https://www.open-accessibility.org/de/ This seems the simplest solution since we don't have much to translate.

2. host the site elsewhere like Netlify and use a plugin (there are few to choose from)

Ref using Poedit: I have found only one plugin that does this and it hasn't been updated in 3 years and if there is (or later develops after Jekyll updates) a bug it will be more costly to fix so I wouldn't advise taking this route

**Comment by EPajares** [comment]
Thanks for this update Ivan. Ok I see. Considering the fact that we are not going to translate all the content but rather focus on the main page at the moment I would propose that we go for option 1.
