### ISSUE TITLE
Increase limit of characters for heading of printed map

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#518]
Currently the heading can only be quite short. Could we increase this or will it not fit into the available space?

**Comment by EPajares** [comment]
@majkshkurti @UJehle

**Comment by UJehle** [comment]
@majkshkurti 
I increased the text box size, but there seams to be the same issue as for the legend text before. I just could not find this setting in the config file. Do you know where this is stored?

**Comment by majkshkurti** [comment]
@UJehle For legend this have to be adjusted in config file, because legend is a subreport. 
Although it shouldn't be the case for the text field. Changing the width in report template should work. 
Currently in A4 Portrait it takes approx. 30 characters, then i guess it breaks in a new line that isn't visible because of the legend.
However i did some test with the increased width in A4 Portrait Report. 
I think that when the line breaks it also takes some word/letters  from the first line and moves it to the second one, which isn't visible. 
The breakpoint isn't exactly at the end of the textfield though. 
Maybe there is a setting for it to change, but we have to check in Jaspersoft.

**Comment by EPajares** [comment]
I think we can close this right?
