### ISSUE TITLE
Issue with cron job using new updated cron container

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#630]
I was changing the docker image of the cron container 471456a in the feature/buildings_editing to be able to run all setup scripts in this container. Though the issue now is again with the Python interpreter and cron. We need to do some testing here.

**Comment by majkshkurti** [comment]
@EPajares 
The DB docker image which we are inheriting from doesn't have the cron service installed, so it will not run at all. 
We can install it though when building cron docker image (**apt-get install cron**). 
After installing it, the python path should also change in crontab file, since it is different in db image. 
I think it should reference **/usr/bin/python3.7** instead of **/usr/local/bin/python**

**Comment by EPajares** [comment]
Great! We fixed this.
