### ISSUE TITLE
Fix Fitness stations

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#707]
Not all fitness stations where added as some are not surrounded by an area. We need to improve the data preparation here.

**Comment by EPajares** [comment]
@rafleo2008

**Comment by rafleo2008** [comment]
The new commit include all the open fitness stations. However, there are some issues to be considered first.

The idea to group by area was applied in order to assign a common name to each complex, and count only one point per complex, but there are some complex without a clear boundary, and there, GOAT will count each point individually because they don't share name.

Moreover, I was thinking to build a kind of "grouping radius", but we have all types of cases, with fitness stations so close each other (10m) to other cases where the different stations are distributed along a big area (up to 200m) ([here](https://www.openstreetmap.org/#map=18/48.20869/11.32213)), therefore, for now, I have decided not to apply it.

Now, the data has been improved, but still we have to deal with this considerations.

**Comment by EPajares** [comment]
Searching outdoor gyms these days as replacement for the closed gyms I realized this issue gets more important :) I think we should map the outdoor gyms as areas according the OSM guidelines as discussed. @rafleo2008 could you do it?
