### ISSUE TITLE
Automatic classification of "Krippen" 

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#732]
Kindergartens that have "Krippe" in their name should automatically be classified as Krippe. 
For example:
https://www.openstreetmap.org/edit?editor=id&node=4323866224#map=20/48.14457/11.55788
https://www.openstreetmap.org/edit?editor=id&node=1501199732#map=20/48.11315/11.53252
https://www.openstreetmap.org/edit?editor=id&node=1501199732#map=20/48.11315/11.53252

**Comment by rafleo2008** [comment]
True... there are some nursery points classified as "kindergarten", this happened because the lookup values were attached only to look names on the right part of the text string, like "Städtische kinderkrippe". Other names like "Kinderkrippe Spatzennest" were wrongly discarded. This has been done to avoid reclassificate Kindergartens as nursery, for example "kinderkripe und kindergarten".

I did a small change in the reclassification, now it searches for "krippe" and "kinderkrippe"  at any part of the name string. But we have 4 misclassified kindergartens there. (In contrast,  we have gained more than 40 on the other side), therefore, I consider itthis solution is better than before and cover more correct cases.

**Comment by UJehle** [comment]
Thanks @rafleo2008 , 40 additionally classified Krippen is already a good result! I see, the double use of an amenity is an issue .. If we agree that the correct classification of Kindergartens is more important than Krippen then maybe a way to solve this could be to classify the POI as "Kindergarten" as soon as this word is in the string, as a higher condition than looking for "Krippe". Or we display two icons (which would get a bit more tricky, but more accurate), e.g. by copying the column of the amenity (having one column for the Kindergarten and one column for the Krippe) and slightly adjust the geom of one of it, so that the second icon gets visible and not hidden below the first icon.

**Comment by rafleo2008** [comment]
Yes, I think this classification is better than the wrong classification of these 40 nurseries. About that point, there is an issue where we have been discussing the different alternatives for those POIS that could represent more than one amenity https://github.com/goat-community/goat/issues/633 .

**Comment by EPajares** [comment]
We should finalize this if possible within this week. As we still have the issue that many nurseries are missing. Please work on feature/data_preparation

**Comment by rafleo2008** [comment]
I have been working on this, it is almost done but I've found some troubles I still have to solve, I expect to finish it by the next monday.

**Comment by EPajares** [comment]
How are we doing with this one? It would be great to ship this the new release scheduled this week. Can I merge the code from the data_preparation branch?

**Comment by rafleo2008** [comment]
As we solved the missing Krippen with the implementation of duplicated POIS, and proposed the translation scripts, I think we could close this issue.
